config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:new, :create, :index, :show]

  resources :replies, only: [:create]

  root 'topics#index'

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  validates :body, presence: true

  belongs_to(
  :repliable,
  polymorphic: true
  )

  has_many(
  :replies, as: :repliable, dependent: :destroy
  )


end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, :body, presence: true

  has_many(
  :replies, as: :repliable, dependent: :destroy
  )


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def create
    @reply = Reply.new(body: params[:reply][:body],
                      repliable_id: params[:reply][:repliable_id],
                      repliable_type: params[:reply][:repliable_type])
    @reply.save
    redirect_to topic_url(params[:reply][:topic_id])
  end

  def destroy
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
    render :index
  end

  def new
    @topic = Topic.new
    render :new
  end

  def create
    @topic = Topic.new(top_params)
    if @topic.save
      redirect_to topic_url(@topic.id)
    else
      flash[:errors] = @topic.errors.full_messages
      render :new
    end
  end

  def show
    @topic = Topic.find_by(id: params[:id])
    render :show
  end

  private
  def top_params
    params.require(:topic).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <style>
    body { background: lightblue; }
    img {margin-left: 40px};
  </style>
<head>
  <title>Thechan</title>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
<ul>

  <% flash[:errors].each do |error| %>
    <li><%=error%></li>
  <% end %>

</ul>
<% end %>

app/views/topics/index.html.erb
<h1>Welcome to Jackie Chan</h1>
<img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTFsdymmy8jUhaqaeEJ9c-YFv1Oi-sFEyt9SIl2T1FjBvdMOk9XyAG1jMzD"
width="260" height="180"><br>

<a href='/topics/new'>Start a new Thread</a>

<hr size="10" noshade>


<% @topics.each do |topic| %>
  <hr>
  <a href="<%=topic_url(topic.id)%>"><b><%=topic.title%></b></a>
  (<%=topic.replies.length.to_s%> replies)
  <p>
    <%=topic.body%>
  </p>
  <hr>


  <ul>
      <% for i in 0...3 do %>
            <% break if topic.replies[i].nil? %>
            <li>
                <b>Annonymous#<%=topic.replies[i].id%>:</b><br>
                <%=topic.replies[i].body%>
            </li>
      <% end %>
  </ul>


<% end %>

app/views/topics/new.html.erb
<h1>Make a new thread</h1>

<%= render 'shared/errors' %>

<form action='/topics' method="POST">
  <label>Title
    <input type="text" name="topic[title]" value="<%=@topic.title%>">
  </label>
  <br>
  <br>
    Body
    <br>
    <textarea name="topic[body]" rows="30" cols="50"><%=@topic.body%></textarea><br>
  <button>Submit Thread</button>
</form>
<hr>
<br>

<a href="/topics">Back to Homepage</a>

app/views/topics/show.html.erb
<h2> <%= @topic.title %> </h2>
  <p>
    <%=@topic.body%>
  </p>
  <hr>
  <!-- list of replies goes here -->
    <ul>
      <% @topic.replies.each do |reply| %>
        <li>
          <b>Annonymous#<%=reply.id%>:</b><br>
          <%=reply.body%>
          <!-- replies to replies goes here. -->
        </li>
      <% end %>
    </ul>

  <br>
  <br>
  <hr size="20" noshade>

  <form action="<%=replies_url%>" method="POST">
    <input type="hidden" name="reply[repliable_id]" value="<%=@topic.id%>">
    <input type="hidden" name="reply[repliable_type]" value="Topic">
    <input type="hidden" name="reply[topic_id]" value="<%=@topic.id%>">
    <label>Reply to the Thread<br>
    <textarea name="reply[body]" rows="10" cols="30"></textarea><br>
    <button>Submit</button>
  </label>
  </form>

  <br>
  <a href="/topics">Back to Main Page</a>